version: '3.8'

services:
  pc_backend:
    image: domin82/place-check-backend
    ports:
      - "5000:8080"
    networks:
      - pc_network

  pc_worker:
    image: domin82/place-check-worker:latest
    ports:
      - "5001:8080"
    networks:
      - pc_network

  pc_mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=!Kofi1109!
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - pc_network

volumes:
  mssql_data:
    driver: local

networks:
  pc_network:
    driver: bridge
