name: Build and Deploy PlaceCheck

on:
  push:
    branches: [ main ]
    paths:
      - 'PlaceCheck.Backend/**'
      - 'PlaceCheck.Worker/**'
  pull_request:
    branches: [ main ]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      backend_version: ${{ steps.get_version.outputs.backend_version }}
      worker_version: ${{ steps.get_version.outputs.worker_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            backend:
              - 'PlaceCheck.Backend/**'
            worker:
              - 'PlaceCheck.Worker/**'

      - name: Debug file changes
        run: |
          echo "Modified backend files:"
          echo "${{ steps.changed-files.outputs.backend_all_modified_files }}"
          echo "Modified worker files:"
          echo "${{ steps.changed-files.outputs.worker_all_modified_files }}"
      
      - name: Load and update versions
        id: get_version
        run: |
          # Backend version update
          if [[ -n "${{ steps.changed-files.outputs.backend_all_modified_files }}" ]]; then
            echo "Changes detected in Backend"
            cd PlaceCheck.Backend
            CURRENT_VERSION=$(grep IMAGE_VERSION .env | cut -d'=' -f2)
            echo "Current Backend version: $CURRENT_VERSION"
            NEW_VERSION="v$(echo ${CURRENT_VERSION#v} | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"
            echo "New Backend version: $NEW_VERSION"
            sed -i "s/IMAGE_VERSION=.*/IMAGE_VERSION=$NEW_VERSION/" .env
            echo "backend_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            cd ..
          else
            echo "No changes in Backend"
            CURRENT_VERSION=$(grep IMAGE_VERSION PlaceCheck.Backend/.env | cut -d'=' -f2)
            echo "backend_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          fi
          
          # Worker version update
          if [[ -n "${{ steps.changed-files.outputs.worker_all_modified_files }}" ]]; then
            echo "Changes detected in Worker"
            cd PlaceCheck.Worker
            CURRENT_VERSION=$(grep IMAGE_VERSION .env | cut -d'=' -f2)
            echo "Current Worker version: $CURRENT_VERSION"
            NEW_VERSION="v$(echo ${CURRENT_VERSION#v} | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"
            echo "New Worker version: $NEW_VERSION"
            sed -i "s/IMAGE_VERSION=.*/IMAGE_VERSION=$NEW_VERSION/" .env
            echo "worker_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            cd ..
          else
            echo "No changes in Worker"
            CURRENT_VERSION=$(grep IMAGE_VERSION PlaceCheck.Worker/.env | cut -d'=' -f2)
            echo "worker_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          fi

          # Show final versions
          echo "Final .env contents:"
          echo "Backend .env:"
          cat PlaceCheck.Backend/.env
          echo "Worker .env:"
          cat PlaceCheck.Worker/.env

      - name: Commit version changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "PlaceCheck.Backend/.env" "PlaceCheck.Worker/.env"
          git commit -m "Bump version [skip ci]" || echo "No changes to commit"
          git push

  build-and-push:
    needs: version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: backend
            path: PlaceCheck.Backend
            dockerfile_path: ./PlaceCheck.Backend/PlaceCheck.WebApi/Dockerfile
          - service: worker
            path: PlaceCheck.Worker
            dockerfile_path: ./PlaceCheck.Worker/PlaceCheck.Worker/Dockerfile
    
    steps:
      - uses: actions/checkout@v3

      - name: Load service configuration
        id: config
        shell: bash
        run: |
          cd ${{ matrix.path }}
          if [ -f ".env" ]; then
            echo "Loading config from .env file"
            cat .env
            export $(cat .env | xargs)
            DOCKER_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME"
            DOCKER_IMAGE=$(echo "$DOCKER_IMAGE" | tr -d '[:space:]')
            echo "docker_image=$DOCKER_IMAGE" >> $GITHUB_OUTPUT
            if [ "${{ matrix.service }}" = "backend" ]; then
              echo "version=${{ needs.version.outputs.backend_version }}" >> $GITHUB_OUTPUT
            else
              echo "version=${{ needs.version.outputs.worker_version }}" >> $GITHUB_OUTPUT
            fi
          else
            echo "Error: .env file not found in ${{ matrix.path }}"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        if: matrix.service == 'backend'
        uses: docker/build-push-action@v4
        env:
          DOCKER_IMAGE: ${{ steps.config.outputs.docker_image }}
          VERSION: ${{ steps.config.outputs.version }}
        with:
          context: ./PlaceCheck.Backend
          file: ./PlaceCheck.Backend/PlaceCheck.WebApi/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: "${{ steps.config.outputs.docker_image }}:${{ steps.config.outputs.version }},${{ steps.config.outputs.docker_image }}:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Worker
        if: matrix.service == 'worker'
        uses: docker/build-push-action@v4
        env:
          DOCKER_IMAGE: ${{ steps.config.outputs.docker_image }}
          VERSION: ${{ steps.config.outputs.version }}
        with:
          context: ./PlaceCheck.Worker
          file: ./PlaceCheck.Worker/PlaceCheck.Worker/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: "${{ steps.config.outputs.docker_image }}:${{ steps.config.outputs.version }},${{ steps.config.outputs.docker_image }}:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max